#
# Copyright (C) 2018 Tobias Tefke
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Simple tool for finding proprietary files

import os
import os.path

proprietaries = []

print("WARNING: all paths have to be absolute!")
systemImage = input("Please enter the location of the system image: ")
mountPoint = input("Please enter a mount point for the image: ")
outDirectory = input("Please enter the location of the system folder built by the build system: ")
propFiles = input("Please enter a location where the proprietary files list should be saved: ")

# Mount system image
print("Root privileges needed for mounting the system image")
mountCmd = str("sudo mount -r -o loop " + systemImage + " " + mountPoint)
os.system(mountCmd)

# Walk system image
print("Walking system image")
for dirName, subdirList, fileList in os.walk(mountPoint):
        for fname in fileList:            
            # Get real file name
            fname = dirName + "/" + fname
            dropChars = len(mountPoint)
            currentFile = fname[dropChars:]
            
            # Get built file name
            builtFile = outDirectory + "/" + currentFile
            
            # Check if file does not exist in out directory
            if not os.path.isfile(builtFile):
                propFile = currentFile[1:] 
                # Skip some unneccessary files
                if "app/" in propFile:
                    continue
                if propFile.endswith(".art"):
                    continue
                if propFile.endswith(".oat"):
                    continue
                if propFile.endswith(".odex"):
                    continue
                if propFile.endswith(".vdex"):
                    continue
                if propFile.startswith("media/"):
                    continue
                if propFile.startswith("customize/"):
                    continue
                if propFile.startswith("etc/.demoflo/"):
                    continue
                if propFile == "etc/perf/whitelistedapps.xml":
                    continue
                if propFile == "etc/preferred-apps/google.xml":
                    continue
                if "permissions/" in propFile:
                    continue
                if propFile.startswith("etc/security/"):
                    continue
                if propFile.startswith("fonts/"):
                    continue
                if propFile.startswith("framework/"):
                    print("Skipped frameworks file {}".format(propFile))
                    continue
                if propFile.startswith("usr/srec/"):
                    continue
                if "vndk-sp/" in propFile:
                    continue
                proprietaries.append(propFile)

# Write list
print("Writing proprietaries list")
with open (propFiles, "w") as blobs:
    blobs.write("# Blobs list autogenerated by find-proprietary-files.py\n\n")
    for element in proprietaries:
        blobs.write(element)
        blobs.write("\n")

# Unmount system image
print("Unmounting system image")
unmountCmd = str("sudo umount " + mountPoint)
os.system(unmountCmd)
